Fix Reconnect ReliableProducer in case leader is down
rabbitmq/rabbitmq-stream-dotnet-client pull request #163
Opened 2022-09-07 14:41 UTC by Gsantomaggio

Fixes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/150

Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>

2022-09-07 14:42 UTC, Gsantomaggio commented
@ricsiLT when you have time, can you please try it?

still work in progress but it should work :) !

2022-09-07 19:44 UTC, ricsiLT commented
Had this issue today, would have been perfect :D Will try to deploy tomorrow and cause and issue with a forced restart ^^

2022-09-12 20:56 UTC, lukebakken requested changes
I don't think I see the correct behavior. I do see a reconnection being made, but the "Stream" page in the management UI only shows one entry, even after I restart the node I stopped:

![image](https://user-images.githubusercontent.com/514926/189756831-01185226-60d5-410b-b9eb-670dbf75654b.png)

In addition, the page starts returning a 500 error (not good), and I see some log messages like this which seem fishy:

```
docker-node0-1  | 2022-09-12 20:53:47.105297+00:00 [debug] <0.611.0> Marking RabbitMQ as running
docker-node0-1  | 2022-09-12 20:53:47.105320+00:00 [debug] <0.611.0> Change boot state to `ready`
docker-node0-1  | 2022-09-12 20:53:47.105401+00:00 [debug] <0.133.0> Boot state/systemd: notifying of state `ready`
docker-node0-1  | 2022-09-12 20:53:47.230426+00:00 [debug] <0.9.0> Time to start RabbitMQ: 28938365 us
docker-node0-1  | 2022-09-12 20:53:47.426391+00:00 [debug] <0.554.0> rabbit_stream_coordinator: pre_vote election called for in term 1
docker-node0-1  | 2022-09-12 20:53:47.426585+00:00 [debug] <0.554.0> rabbit_stream_coordinator: follower -> pre_vote in term: 1 machine version: 3
docker-node0-1  | 2022-09-12 20:53:47.426747+00:00 [debug] <0.554.0> rabbit_stream_coordinator: pre_vote granted #Ref<0.2376076381.66060290.251237> for term 1 votes 1
docker-node1-1  | 2022-09-12 20:53:47.427289+00:00 [debug] <0.1019.0> rabbit_stream_coordinator declining pre-vote to {rabbit_stream_coordinator,rabbit@node0} for term 1, current term 2
docker-node0-1  | 2022-09-12 20:53:47.434834+00:00 [debug] <0.554.0> rabbit_stream_coordinator: pre_vote -> follower in term: 2 machine version: 3
docker-node0-1  | 2022-09-12 20:53:47.435044+00:00 [debug] <0.554.0> rabbit_stream_coordinator: is not new, setting election timeout.
docker-node0-1  | 2022-09-12 20:53:47.435193+00:00 [info] <0.554.0> rabbit_stream_coordinator: follower did not have entry at 29 in 2. Requesting {rabbit_stream_coordinator,rabbit@node2} from 11
docker-node0-1  | 2022-09-12 20:53:47.435425+00:00 [info] <0.554.0> rabbit_stream_coordinator: detected a new leader {rabbit_stream_coordinator,rabbit@node2} in term 2
docker-node0-1  | 2022-09-12 20:53:47.435564+00:00 [debug] <0.554.0> rabbit_stream_coordinator: follower -> await_condition in term: 2 machine version: 3
docker-node2-1  | 2022-09-12 20:53:47.435878+00:00 [debug] <0.1364.0> rabbit_stream_coordinator: setting last index to 10,  next_index 11 for {rabbit_stream_coordinator,rabbit@node0}
docker-node0-1  | 2022-09-12 20:53:47.437594+00:00 [debug] <0.554.0> rabbit_stream_coordinator: await_condition -> follower in term: 2 machine version: 3
docker-node0-1  | 2022-09-12 20:53:47.437785+00:00 [debug] <0.554.0> rabbit_stream_coordinator: is not new, setting election timeout.
docker-node0-1  | 2022-09-12 20:53:47.438991+00:00 [debug] <0.554.0> rabbit_stream_coordinator: enabling ra cluster changes in 2
docker-node0-1  | 2022-09-12 20:53:47.439137+00:00 [debug] <0.554.0> rabbit_stream_coordinator: unknown command {nodedown,rabbit@node0}
docker-node1-1  | 2022-09-12 20:54:18.814975+00:00 [debug] <0.1232.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
docker-node1-1  | 2022-09-12 20:54:18.836385+00:00 [debug] <0.1234.0> User 'guest' authenticated successfully by backend rabbit_auth_ba
```

`unknown command` makes me nervous!

2022-09-13 06:58 UTC, Gsantomaggio commented
I think the problem is that you are using only two nodes; with one node, it doesn't reach the quorum. I will investigate

2022-09-13 16:49 UTC, lukebakken approved these changes
Great work @Gsantomaggio

2022-09-13 16:49 UTC, merged