Implement Deduplicating Producer
rabbitmq/rabbitmq-stream-dotnet-client pull request #234
Opened 2023-02-09 15:58 UTC by Gsantomaggio

Fixes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/227

Implement the `DeduplicationProducer` make the `ProducerConfig.Reference` deprecated.
The `Producer` does not need the `Reference` to work. `Reference` is needed only for the Deduplication part.

The low-level Class is the `RawProducer` class; this class sets the correct parameters to enable the deduplication and to make it easy to use. 

 

Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>

2023-02-11 22:47 UTC, michaelklishin commented
Should this be `DeduplicatingProducer`, a producer that deduplicates messages vs. a producer of deduplication? :) Sorry.

2023-02-12 16:03 UTC, lukebakken requested changes
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/234#issuecomment-1426891808

Thanks!

2023-02-13 11:27 UTC, Zerpet submitted a review, later dismissed
Looking good. Left a few cosmetic suggestions, but up to you if you want to merge as-is.

2023-02-13 11:27 UTC, Zerpet commented on RabbitMQ.Stream.Client/Reliable/Producer.cs
>          }
If we are not locking the semaphore in this method, can we delete this `finally` block?

2023-02-13 11:27 UTC, Zerpet commented on Tests/DeduplicationProducerTests.cs
> +*/
I guess we can remove those? 🙈

2023-02-13 11:52 UTC, Gsantomaggio commented
Thanks @Zerpet fixed here https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/234/commits/1780afd2e044a06618e6625efb2433fe25d931d2

2023-02-13 13:38 UTC, merged