Refactor
rabbitmq/rabbitmq-stream-dotnet-client pull request #89
Opened 2022-03-16 23:44 UTC by sirh3e

As discussed in #85

2022-03-17 08:27 UTC, Gsantomaggio commented
You need to execute `dotnet format` this is why the CI fails.
I need to add the documentation/make files for that. 
Thank you

2022-03-22 13:06 UTC, Gsantomaggio commented
@sirh3e Can you please give me the grant to push. I need to change the `approval.txt` file
thank you.

p.s. I will squash all the commits in one!

2022-03-22 13:41 UTC, sirh3e commented
@Gsantomaggio Sorry, but I'm not sure whether I should grant you permission on this pr or on my fork?

2022-03-22 13:46 UTC, lukebakken commented
@sirh3e please follow these instructions to allow pushes to your fork for your PR branches:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

That way we can clean up for you. Thanks!

2022-03-22 13:48 UTC, lukebakken requested changes

2022-03-22 13:48 UTC, lukebakken commented on Makefile
> +build: format
I'd rather not have the `build` target depend on the `format` target.

2022-03-22 14:13 UTC, sirh3e commented
![image](https://user-images.githubusercontent.com/24867927/159501083-32bd4f95-97f8-4237-9cb8-2843458c00ed.png)

As you see in this image there is no checkbox to check for "Allow edits from maintainers"

Doc Ref:
![image](https://docs.github.com/assets/cb-44583/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png)

2022-03-22 14:18 UTC, lukebakken commented
That's strange! OK I will open a new PR with your changes, one minute.

2022-03-22 14:24 UTC, lukebakken commented
Please see #91

2022-03-22 14:24 UTC, closed without merging